// Code generated by protoc-gen-go. DO NOT EDIT.
// source: challenge.proto

package generated

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StringRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringRequest) Reset()         { *m = StringRequest{} }
func (m *StringRequest) String() string { return proto.CompactTextString(m) }
func (*StringRequest) ProtoMessage()    {}
func (*StringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_challenge_2db5a794910b05f1, []int{0}
}
func (m *StringRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringRequest.Unmarshal(m, b)
}
func (m *StringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringRequest.Marshal(b, m, deterministic)
}
func (dst *StringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringRequest.Merge(dst, src)
}
func (m *StringRequest) XXX_Size() int {
	return xxx_messageInfo_StringRequest.Size(m)
}
func (m *StringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StringRequest proto.InternalMessageInfo

func (m *StringRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type StringResponse struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringResponse) Reset()         { *m = StringResponse{} }
func (m *StringResponse) String() string { return proto.CompactTextString(m) }
func (*StringResponse) ProtoMessage()    {}
func (*StringResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_challenge_2db5a794910b05f1, []int{1}
}
func (m *StringResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringResponse.Unmarshal(m, b)
}
func (m *StringResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringResponse.Marshal(b, m, deterministic)
}
func (dst *StringResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringResponse.Merge(dst, src)
}
func (m *StringResponse) XXX_Size() int {
	return xxx_messageInfo_StringResponse.Size(m)
}
func (m *StringResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StringResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StringResponse proto.InternalMessageInfo

func (m *StringResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*StringRequest)(nil), "generated.StringRequest")
	proto.RegisterType((*StringResponse)(nil), "generated.StringResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StringmanipClient is the client API for Stringmanip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StringmanipClient interface {
	// A remote procedure call which accepts a StringRequest, reverses its member data, and returns the reversed string in StringResponse
	Reversed(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringResponse, error)
}

type stringmanipClient struct {
	cc *grpc.ClientConn
}

func NewStringmanipClient(cc *grpc.ClientConn) StringmanipClient {
	return &stringmanipClient{cc}
}

func (c *stringmanipClient) Reversed(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringResponse, error) {
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, "/generated.stringmanip/reversed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StringmanipServer is the server API for Stringmanip service.
type StringmanipServer interface {
	// A remote procedure call which accepts a StringRequest, reverses its member data, and returns the reversed string in StringResponse
	Reversed(context.Context, *StringRequest) (*StringResponse, error)
}

func RegisterStringmanipServer(s *grpc.Server, srv StringmanipServer) {
	s.RegisterService(&_Stringmanip_serviceDesc, srv)
}

func _Stringmanip_Reversed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StringmanipServer).Reversed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/generated.stringmanip/Reversed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StringmanipServer).Reversed(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stringmanip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "generated.stringmanip",
	HandlerType: (*StringmanipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "reversed",
			Handler:    _Stringmanip_Reversed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "challenge.proto",
}

func init() { proto.RegisterFile("challenge.proto", fileDescriptor_challenge_2db5a794910b05f1) }

var fileDescriptor_challenge_2db5a794910b05f1 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xce, 0x48, 0xcc,
	0xc9, 0x49, 0xcd, 0x4b, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0x4f, 0xcd,
	0x4b, 0x2d, 0x4a, 0x2c, 0x49, 0x4d, 0x51, 0xd2, 0xe4, 0xe2, 0x0d, 0x2e, 0x29, 0xca, 0xcc, 0x4b,
	0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0x4f, 0xce, 0xcf, 0x2b, 0x49,
	0xcd, 0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x95, 0xb4, 0xb8, 0xf8, 0x60,
	0x4a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x71, 0xab, 0x35, 0x0a, 0xe0, 0xe2, 0x2e, 0x06, 0xab,
	0xcd, 0x4d, 0xcc, 0xcb, 0x2c, 0x10, 0x72, 0xe4, 0xe2, 0x28, 0x4a, 0x2d, 0x4b, 0x2d, 0x2a, 0x4e,
	0x4d, 0x11, 0x92, 0xd0, 0x83, 0xdb, 0xae, 0x87, 0x62, 0xb5, 0x94, 0x24, 0x16, 0x19, 0x88, 0x4d,
	0x4a, 0x0c, 0x49, 0x6c, 0x60, 0xa7, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xb5, 0x6a,
	0xc1, 0xcd, 0x00, 0x00, 0x00,
}
